### ISSUE TITLE
feat: launch

### ISSUE THREAD

**Issue by arein** [WalletConnect/bouncer#1]
- [x] Deploy service
- [x] Implement basic APIs
- [x] Adapt to spec
- [x] Serve iFrame
- [x] Serve JS in iFrame
- [ ] Authentication
- [ ] Project ID Validation
