### ISSUE TITLE
feat: enable content-security policy

### ISSUE THREAD

**Issue by arein** [WalletConnect/bouncer#2]
the "web enclave" may only be served on the domains the developer declares and owns.

This requires the `HTTP GET /<projectId>` route to append a [Content-Security Policy Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors).

Specifically this could look like `Content-Security-Policy: frame-ancestors [<space separated list of sources>](https://react-app.walletconnect.com/) https://react-wallet.walletconnect.com/;` for our web example project id.

- [x] Hardcode a response of `Content-Security-Policy: frame-ancestors [<space separated list of sources>](https://react-app.walletconnect.com/) https://react-wallet.walletconnect.com/;` **to unblock the JS dapp-side**
- [ ] Actually validate the project id on the `HTTP GET /<projectId>` route and integrate with https://github.com/WalletConnect/cerberus.git and flush the data into the existing Redis cache
- [ ] Update the CloudFlare `/internal` API to respond with a list of verified domains (Cloud team will add proper verified domains in https://github.com/WalletConnect/cloud-app/issues/37)
- [ ] Use the actual list of verified domains in the respond not the hardcoded one

**Comment by adahamilton1** [comment]
Does this mean dapp devs MUST register their project on the WalletConnect explorer on cloud.walletconnect.com before they can use WalletConnect? `web3modal/standalone` just failed to open on our dapp site on firefox because `verify.walletconnect.com/<project-id>` failed with `NS_ERROR_CSP_FRAME_ANCESTOR_VIOLATION` probably because the content-security-policy is `frame-ancestors https://react-app.walletconnect.com` only

**Comment by chris13524** [comment]
@adahamilton1 all dApps have needed a project ID for a while: https://docs.walletconnect.com/2.0/web3modal/advanced/standalone/sign/installation#obtain-project-id

**Comment by adahamilton1** [comment]
> @adahamilton1 all dApps have needed a project ID for a while: https://docs.walletconnect.com/2.0/web3modal/advanced/standalone/sign/installation#obtain-project-id

it's not just the project ID, I was referring to registering the project on the WalletConnect explorer and submitting it for review by WalletConnect so that the domain allowlists work for `Content-Security-Policy: frame-ancestors ...`

![image](https://user-images.githubusercontent.com/128478647/234575466-25fdf256-37e3-43d1-b679-03cb75503b6c.png)
